export const metadata = {
  title: "Terms of Service — LeaseGuard",
  description:
    "Terms of Service for LeaseGuard, the AI-powered CAM audit tool for commercial tenants.",
};

export default function TermsPage() {
  return (
    <main className="flex flex-col items-center px-4 py-20 sm:py-28">
      <article className="max-w-2xl w-full">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-gray-400 mb-10">
          Last updated: March 2026
        </p>

        <section className="space-y-8 text-sm text-gray-600 leading-relaxed">
          <div>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              1. Service Description
            </h2>
            <p>
              LeaseGuard provides AI-powered CAM (Common Area Maintenance)
              audit analysis for commercial lease tenants. The service analyzes
              uploaded lease and reconciliation documents to identify potential
              billing discrepancies, including overcharges, excluded expense
              violations, and cap exceedances.
            </p>
          </div>

          <div>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              2. Not Legal or Accounting Advice
            </h2>
            <p>
              LeaseGuard is an informational tool only. The analysis, findings,
              and reports generated by LeaseGuard do not constitute legal,
              accounting, or professional advice. Results depend on document
              clarity and lease structure. You should consult with qualified
              professionals before taking any action based on the results.
            </p>
          </div>

          <div>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              3. Accuracy and Limitations
            </h2>
            <p>
              While we strive to provide accurate analysis, LeaseGuard uses
              AI-based document extraction and comparison. Results may vary
              depending on document quality, formatting, and complexity. We do
              not guarantee the accuracy or completeness of any findings.
              Each audit includes a confidence indicator to help you assess
              reliability.
            </p>
          </div>

          <div>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              4. Payments and Refunds
            </h2>
            <p>
              The Free Audit Preview is available at no cost. The Full Evidence
              Report is available as a one-time purchase of $49 per audit.
              There are no subscriptions, recurring charges, or hidden fees.
              Payments are processed securely through our payment provider.
              Refund requests are handled on a case-by-case basis — contact us
              at support@leaseguard.ai.
            </p>
          </div>

          <div>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              5. Uploaded Documents
            </h2>
            <p>
              You are responsible for ensuring you have the right to upload any
              documents submitted to LeaseGuard. Uploaded documents are used
              solely to perform your audit and generate your report. We handle
              uploaded documents in accordance with our{" "}
              <a href="/privacy" className="text-blue-700 hover:underline">
                Privacy Policy
              </a>
              .
            </p>
          </div>

          <div>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              6. Limitation of Liability
            </h2>
            <p>
              LeaseGuard is provided &ldquo;as is&rdquo; without warranties of
              any kind, express or implied. We are not liable for any damages
              arising from the use of our service, including but not limited to
              direct, indirect, incidental, or consequential damages.
            </p>
          </div>

          <div>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              7. Changes to These Terms
            </h2>
            <p>
              We may update these terms from time to time. Continued use of
              LeaseGuard after changes constitutes acceptance of the updated
              terms.
            </p>
          </div>

          <div>
            <h2 className="text-base font-semibold text-gray-900 mb-2">
              8. Contact
            </h2>
            <p>
              Questions about these terms? Contact us at{" "}
              <a
                href="mailto:support@leaseguard.ai"
                className="text-blue-700 hover:underline"
              >
                support@leaseguard.ai
              </a>
              .
            </p>
          </div>
        </section>
      </article>
    </main>
  );
}
